### ISSUE TITLE
Simulation Service Crashes on Creation of new Simulated Devices

### ISSUE THREAD

**Issue by spryor** [Azure/pcs-remote-monitoring-webui#379]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
Creating a new simulated device appears to crash the SimulationService. I encounter this issue from the UI. Perhaps this is an error in the way the UI is making the call. I will include the request when I have a saved version of it.

```
Unhandled Exception: System.AggregateException: One or more errors occurred. () ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubClientException ---> System.Net.Sockets.SocketException: Success
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<CloseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.GateKeeperDelegatingHandler.<CloseAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceClient.<DisconnectAsync>d__17.MoveNext() in /Users/delucato/workspace/pcs/device-simulation-dotnet/Services/DeviceClient.cs:line 148
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.SimulationAgent.Simulation.DeviceActor.Stop() in /Users/delucato/workspace/pcs/device-simulation-dotnet/SimulationAgent/Simulation/DeviceActor.cs:line 285
   at Microsoft.Azure.IoTSolutions.DeviceSimulation.SimulationAgent.Simulation.DeviceStatusLogic.SendTelemetry.Run(Object context) in /Users/delucato/workspace/pcs/device-simulation-dotnet/SimulationAgent/Simulation/DeviceStatusLogic/SendTelemetry.cs:line 92
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

![image](https://i.imgflip.com/cjey8.jpg)

**Comment by timlaverty** [comment]
done.  
![image](https://user-images.githubusercontent.com/5084013/32034243-52faa9ae-b9c6-11e7-8fcf-7390bca6358e.png)
